server:
  port: 8889


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    hots: 127.0.0.1
    port: 6379
  security:
    user:
      name: admin
      password: 123456

github:
  client:
    id: "3b6ffe53042b2e77e356"
    secret: "d03a893e5e754d2ffb0ac66a76cacbc49c1eaf6d"
  redirecturi: "http://localhost:8889/callback"

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  #  type-aliases-package: com.lean.lumen
  configuration:
    map-underscore-to-camel-case: true

logging:
  file: lumenCommunity.log
  level:
    root: info
    com:
      lean:
        lumen:
          mapper: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql